services:
  video-recorder:
    container_name: ${VIDEO_RECORDER_CONT_NAME}
    image: ${VIDEO_RECORDER_IMG_NAME}
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - DISK_CAPACITY_CHECK_INTERVAL=${DISK_CAPACITY_CHECK_INTERVAL}
      - AVAILABLE_FILE_EXT=${AVAILABLE_FILE_EXT}
    volumes:
      - "${VIDEO_RECORDER_LOG_PATH_ROOT}:/recorder/logs"
      - "${VIDEO_RECORDER_CONF_PATH_ROOT}:/recorder/config:ro"
      - "${VIDEO_RECORDER_VIDEO_PATH_ROOT}:/recorder/video"
    network_mode: host