camera {
    cam_name CAM-01;
    cam_ip HERE_CAMERA_IP;
    cam_port 554;
    cam_rtsp_path Streaming/Channels/101;
    username admin;
    password HERE_CAMERA_PASSWORD;
    video_interval_seconds 60;
    file_ext '.mp4';
}
