name: CI - Checking syntax error (Python)

concurrency:
  group: deploy-${{ github.repository }}
  cancel-in-progress: false

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  package: write

jobs:
  lint-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Syntax check
        run: python -m compileall .