name: CD - Image Build and Deploy

concurrency:
  group: deploy-${{ github.repository }}
  cancel-in-progress: false

on:
  workflow_run:
    workflows: [ "CI - Checking syntax error (Python)" ]
    types:
      - completed
  workflow_dispatch:

env:
  IMAGE_NAME: video-recorder
  CONT_NAME: video-recorder

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: [ 'self-hosted' ]
    env:
      TZ: Asia/Seoul
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker build \
            --build-arg GITHUB_ACTOR=${{ github.actor }} \
            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$(date +%Y%m%d%H%M%S) \
            .

      - name: Executing container using Docker Compose
        run: |
          docker compose \
          -f /opt/docker/compose/video-recorder-docker-compose.yml \
          up -d --no-build --pull never \
          $CONT_NAME

      - name: Removing old image
        run: |
          docker images $IMAGE_NAME --format "{{.Repository}}:{{.Tag}}" \
          | grep -E ':[0-9]{14}$' \
          | sort -r \
          | tail -n +6 \
          | xargs -r docker rmi || true

      - name: Flushing docker cache
        run: docker image prune -f